### ISSUE TITLE
Fix big screen table overflow

### ISSUE THREAD

**Issue by m1gnus** [proc-hetta/frontorcolo#1]
Actually there is a ugly fix to make table overflow properly:

```css
    @media (min-width: 768px) {
        td {
            max-width: 250px;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    }

    @media (min-width: 1000px) {
        td {
            max-width: 450px;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    }

    @media (min-width: 1200px) {
        td {
            max-width: 650px;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    }

    @media (min-width: 1400px) {
        td {
            max-width: 850px;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    }
```
make the table overflow work properly
